import DSeparation.DAG.Basic

open Finset

namespace DSeparation

noncomputable section

/-! # DAG Reachability

Descendants, ancestors (including and excluding the node itself), the ancestral
subgraph construction, and leaf deletion with cardinality lemmas.
-/

/-- Nodes reachable from `v`, excluding `v` itself. -/
def descendants (G : DAG) (v : ℕ) : Finset ℕ := by
  classical
  exact G.nodes.filter fun w => w ≠ v ∧ Reachable G v w

/-- Nodes that can reach `v`, excluding `v` itself. -/
def ancestors (G : DAG) (v : ℕ) : Finset ℕ := by
  classical
  exact G.nodes.filter fun u => u ≠ v ∧ Reachable G u v

/-- Nodes that are not descendants of `v`, excluding `v`. -/
def nonDescendants (G : DAG) (v : ℕ) : Finset ℕ :=
  G.nodes \ ({v} ∪ descendants G v)

namespace DAG

/-- Ancestors of a node, including the node itself when it belongs to `G.nodes`. -/
def ancestors (G : DAG) (v : ℕ) : Finset ℕ := by
  classical
  exact G.nodes.filter fun u => Reachable G u v

/-- Nodes in the ancestral subgraph generated by a node set. -/
def ancestralSubgraphNodes (G : DAG) (S : Finset ℕ) : Finset ℕ :=
  S.biUnion fun v => G.ancestors v

/-- The directed subgraph induced by the ancestral node set of `S`. -/
def ancestralSubgraph (G : DAG) (S : Finset ℕ) : DAG where
  nodes := G.ancestralSubgraphNodes S
  edges := G.edges.filter fun e =>
    e.1 ∈ G.ancestralSubgraphNodes S ∧ e.2 ∈ G.ancestralSubgraphNodes S
  edges_subset := by
    intro u v h
    exact (Finset.mem_filter.mp h).2
  acyclic :=
    G.acyclic.mono fun _ _ h => (Finset.mem_filter.mp h).1

/-- Delete a vertex and all incident directed edges. -/
def deleteLeaf (G : DAG) (v : ℕ) : DAG where
  nodes := G.nodes.erase v
  edges := G.edges.filter fun e => e.1 ≠ v ∧ e.2 ≠ v
  edges_subset := by
    intro u w h
    rcases Finset.mem_filter.mp h with ⟨hedge, hu_ne, hw_ne⟩
    exact ⟨Finset.mem_erase.mpr ⟨hu_ne, (G.edges_subset hedge).1⟩,
      Finset.mem_erase.mpr ⟨hw_ne, (G.edges_subset hedge).2⟩⟩
  acyclic :=
    G.acyclic.mono fun _ _ h => (Finset.mem_filter.mp h).1

lemma deleteLeaf_card_lt {G : DAG} {v : ℕ} (hv : v ∈ G.nodes) :
    (G.deleteLeaf v).nodes.card < G.nodes.card := by
  simpa [DAG.deleteLeaf] using Finset.card_erase_lt_of_mem hv

lemma mem_ancestors_self (G : DAG) {v : ℕ} (hv : v ∈ G.nodes) :
    v ∈ G.ancestors v := by
  simp [DAG.ancestors, hv, Reachable, Relation.ReflTransGen.refl]

lemma target_mem_nodes_of_reachable {G : DAG} {u v : ℕ}
    (hreach : Reachable G u v) (hu : u ∈ G.nodes) :
    v ∈ G.nodes := by
  induction hreach with
  | refl =>
      exact hu
  | tail _ hstep _ =>
      exact (G.edges_subset hstep).2

lemma mem_ancestralSubgraphNodes_of_mem {G : DAG} {S : Finset ℕ} {v : ℕ}
    (hvS : v ∈ S) (hvG : v ∈ G.nodes) :
    v ∈ G.ancestralSubgraphNodes S := by
  exact Finset.mem_biUnion.mpr ⟨v, hvS, G.mem_ancestors_self hvG⟩

lemma mem_ancestors_of_hasEdge_of_mem_ancestors {G : DAG} {u v s : ℕ}
    (huv : G.HasEdge u v) (hvs : v ∈ G.ancestors s) :
    u ∈ G.ancestors s := by
  classical
  have huG : u ∈ G.nodes := (G.edges_subset huv).1
  have hreach_v_s : Reachable G v s := (Finset.mem_filter.mp hvs).2
  have hreach_u_s : Reachable G u s :=
    (Relation.ReflTransGen.single huv).trans hreach_v_s
  exact Finset.mem_filter.mpr ⟨huG, hreach_u_s⟩

lemma mem_ancestralSubgraphNodes_of_hasEdge_left {G : DAG} {S : Finset ℕ} {u v : ℕ}
    (huv : G.HasEdge u v) (hv : v ∈ G.ancestralSubgraphNodes S) :
    u ∈ G.ancestralSubgraphNodes S := by
  rcases Finset.mem_biUnion.mp hv with ⟨s, hsS, hvs⟩
  exact Finset.mem_biUnion.mpr
    ⟨s, hsS, mem_ancestors_of_hasEdge_of_mem_ancestors huv hvs⟩

end DAG

end

end DSeparation
